### ISSUE TITLE
知乎登录页面作业反馈

### ISSUE THREAD

**Issue by twhy** [Clear-Stream/Clear-Stream.github.io#1]
总体很不错，有一点小建议
1. 右下角反馈按钮其实不需要通过脚本去切换图片，只要通过 
`a:hover { background: url(hover.png) no-repeat center center }` 
这种方式去切换背景图片就好了。

**Comment by Clear-Stream** [comment]
老师 已经修改完成，之前我用的是一个img标签 现在改成了背景元素，可以节省一些代码。
